colors = {
    "catppuccin" : {
        "red": "#F28FAD",
        "purple": "#DDB6F2",
        "blue": "#96CDFB",
        "green": "#ABE9B3",
        "orange": "#F8BD96",
        "yellow": "#FAE3B0",
        "white": "#D9E0EE",
    },
    "dracula" : {
        "red": "#ff5555",
        "purple": "#bd93f9",
        "blue": "#8be9fd",
        "green": "#50fa7b",
        "orange": "#ffb86c",
        "yellow": "#f1fa8c",
        "white": "#f8f8f2",
    },
    "nord" : {
        "red": "#BF616A",
        "purple": "#B48EAD",
        "blue": "#88C0D0",
        "green": "#A3BE8C",
        "orange": "#D08770",
        "yellow": "#EBCB8B",
        "white": "#ECEFF4",
    },
    "gruvbox" : {
        "red": "#FB4934",
        "purple": "#D3869B",
        "blue": "#83A598",
        "green": "#B8BB26",
        "orange": "#FE8019",
        "yellow": "#FABD2F",
        "white": "#EBDBB2",
    },
    "onedark" : {
        "red": "#E06C75",
        "purple": "#C678DD",
        "blue": "#61AFEF",
        "green": "#98C379",
        "orange": "#D19A66",
        "yellow": "#E5C07B",
        "white": "#ABB2BF",
    }
}
